import {
  acceptedEnvelope,
  pageEnvelope,
  successEnvelope,
  uuid,
} from '@shoo/contracts-common';
import { z } from 'zod';
import { HTTP_API_BASE_PATH, pageQuery, previewImpact, projectParams, projectResourceParams } from './common.js';
import {
  captureBatchRequest,
  captureBatchResult,
  checkpointSessionRequest,
  checkpointView,
  completeSessionRequest,
  createWorkUnitRequest,
  failSessionRequest,
  resolveWorkUnitRequest,
  resolveWorkUnitResult,
  resumeSessionRequest,
  sessionView,
  startSessionRequest,
  transitionWorkUnitRequest,
  workUnitView,
} from './continuity.js';
import {
  createProjectRequest,
  deviceView,
  meView,
  memwalBindingView,
  projectView,
  reconcileDelegateRequest,
  reconcileRepositoryRequest,
  registerDelegateRequest,
  registerDeviceRequest,
  verifyMemwalBindingRequest,
} from './identity.js';
import {
  activityItem,
  askRequest,
  askResult,
  buildContextPackRequest,
  contextPackView,
  listActivityQuery,
  pulseView,
} from './intelligence.js';
import {
  acceptMemoryRequest,
  conflictView,
  correctMemoryRequest,
  decisionView,
  listConflictsQuery,
  listMemoriesQuery,
  markCanonicalRequest,
  memoryDetailView,
  memoryView,
  proposeMemoryRequest,
  resolveConflictRequest,
  resolveConflictResult,
  supersedeMemoryRequest,
  supersedeMemoryResult,
} from './memory.js';
import {
  createExportRequest,
  deleteProjectRequest,
  deletionPreviewResult,
  deletionStatusView,
  durableOperationView,
  listDurableOperationsQuery,
  operationView,
  putSyncPolicyRequest,
  reconcileDurableOperationRequest,
  restoreNamespaceRequest,
  syncPolicyPreviewResult,
  syncPolicyView,
} from './platform.js';

/**
 * Machine-readable route registry for the `/v1` surface described in docs/37.
 *
 * The registry is the single source used by the API composition root, the contract
 * snapshot test and generated client fixtures. Adding a route is additive; removing or
 * renaming one is a breaking change requiring a new major path (docs/64 "API versioning").
 */

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';

export interface RouteDefinition {
  readonly method: HttpMethod;
  readonly path: string;
  /** Whether the endpoint mutates state and therefore requires `Idempotency-Key`. */
  readonly mutating: boolean;
  /** Requires recent reauthentication or wallet confirmation (docs/33 "Step-up actions"). */
  readonly stepUp: boolean;
  /** Requires a preview token bound to actor, target version and action (docs/37). */
  readonly previewToken: boolean;
  readonly params?: z.ZodTypeAny;
  readonly query?: z.ZodTypeAny;
  readonly body?: z.ZodTypeAny;
  readonly response: z.ZodTypeAny;
  /** Successful status codes this route may return. */
  readonly statuses: readonly number[];
  readonly summary: string;
}

const p = (suffix: string) => `${HTTP_API_BASE_PATH}${suffix}`;

export const HTTP_ROUTES = {
  getMe: {
    method: 'GET',
    path: p('/me'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    response: successEnvelope(meView),
    statuses: [200],
    summary: 'Current Shoo identity and memberships.',
  },

  createProject: {
    method: 'POST',
    path: p('/projects'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    body: createProjectRequest,
    response: successEnvelope(projectView),
    statuses: [201],
    summary: 'Create or link a Shoo project.',
  },
  getProject: {
    method: 'GET',
    path: p('/projects/:project_id'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    response: successEnvelope(projectView),
    statuses: [200],
    summary: 'Project state and policy summary.',
  },
  reconcileRepository: {
    method: 'POST',
    path: p('/projects/:project_id:reconcile-repository'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    body: reconcileRepositoryRequest,
    response: successEnvelope(projectView),
    statuses: [200],
    summary: 'Resolve a repository path/fingerprint mismatch.',
  },
  registerDevice: {
    method: 'POST',
    path: p('/projects/:project_id/devices'),
    mutating: true,
    stepUp: true,
    previewToken: false,
    params: projectParams,
    body: registerDeviceRequest,
    response: successEnvelope(deviceView),
    statuses: [201],
    summary: 'Register a device public identity and capabilities.',
  },
  revokeDevice: {
    method: 'DELETE',
    path: p('/projects/:project_id/devices/:id'),
    mutating: true,
    stepUp: true,
    previewToken: false,
    params: projectResourceParams,
    response: successEnvelope(deviceView),
    statuses: [200],
    summary: 'Revoke Shoo device access.',
  },
  getMemwalBinding: {
    method: 'GET',
    path: p('/projects/:project_id/memwal-binding'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    response: successEnvelope(memwalBindingView),
    statuses: [200],
    summary: 'Public MemWal binding, delegate and namespace state.',
  },
  verifyMemwalBinding: {
    method: 'POST',
    path: p('/projects/:project_id/memwal-binding:verify'),
    mutating: true,
    stepUp: true,
    previewToken: false,
    params: projectParams,
    body: verifyMemwalBindingRequest,
    response: successEnvelope(memwalBindingView),
    statuses: [200],
    summary: 'Verify wallet/account ownership proof.',
  },
  registerDelegate: {
    method: 'POST',
    path: p('/projects/:project_id/delegates'),
    mutating: true,
    stepUp: true,
    previewToken: false,
    params: projectParams,
    body: registerDelegateRequest,
    response: acceptedEnvelope,
    statuses: [202],
    summary: 'Record a pending device delegate registration.',
  },
  reconcileDelegate: {
    method: 'POST',
    path: p('/projects/:project_id/delegates/:id:reconcile'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    body: reconcileDelegateRequest,
    response: successEnvelope(memwalBindingView),
    statuses: [200],
    summary: 'Reconcile onchain delegate state.',
  },

  resolveWorkUnit: {
    method: 'POST',
    path: p('/projects/:project_id/work-units:resolve'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    body: resolveWorkUnitRequest,
    response: successEnvelope(resolveWorkUnitResult),
    statuses: [200],
    summary: 'Propose, select or create a work unit from context evidence.',
  },
  createWorkUnit: {
    method: 'POST',
    path: p('/projects/:project_id/work-units'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    body: createWorkUnitRequest,
    response: successEnvelope(workUnitView),
    statuses: [201],
    summary: 'Explicit work-unit creation.',
  },
  getWorkUnit: {
    method: 'GET',
    path: p('/projects/:project_id/work-units/:id'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    response: successEnvelope(workUnitView),
    statuses: [200],
    summary: 'Current work-unit state with freshness.',
  },
  transitionWorkUnit: {
    method: 'POST',
    path: p('/projects/:project_id/work-units/:id:transition'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    body: transitionWorkUnitRequest,
    response: successEnvelope(workUnitView),
    statuses: [200],
    summary: 'Authorized work-unit lifecycle transition.',
  },

  startSession: {
    method: 'POST',
    path: p('/projects/:project_id/sessions'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    body: startSessionRequest,
    response: successEnvelope(sessionView),
    statuses: [200, 201],
    summary: 'Idempotent session start.',
  },
  checkpointSession: {
    method: 'POST',
    path: p('/projects/:project_id/sessions/:id:checkpoint'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    body: checkpointSessionRequest,
    response: successEnvelope(checkpointView),
    statuses: [200, 202],
    summary: 'Explicit or adapter-triggered semantic checkpoint.',
  },
  completeSession: {
    method: 'POST',
    path: p('/projects/:project_id/sessions/:id:complete'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    body: completeSessionRequest,
    response: successEnvelope(sessionView),
    statuses: [200, 202],
    summary: 'Record session result separately from work state.',
  },
  failSession: {
    method: 'POST',
    path: p('/projects/:project_id/sessions/:id:fail'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    body: failSessionRequest,
    response: successEnvelope(sessionView),
    statuses: [200],
    summary: 'Record session failure and partial evidence.',
  },
  resumeSession: {
    method: 'POST',
    path: p('/projects/:project_id/sessions/:id:resume'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    body: resumeSessionRequest,
    response: successEnvelope(contextPackView),
    statuses: [200, 202],
    summary: 'Record a resume attempt and deliver continuation context.',
  },

  captureEventsBatch: {
    method: 'POST',
    path: p('/projects/:project_id/capture-events:batch'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    body: captureBatchRequest,
    response: successEnvelope(captureBatchResult),
    statuses: [200, 207],
    summary: 'Device-authenticated bounded capture ingestion.',
  },

  listMemories: {
    method: 'GET',
    path: p('/projects/:project_id/memories'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    query: listMemoriesQuery,
    response: pageEnvelope(memoryView),
    statuses: [200],
    summary: 'Filtered current or history memory search.',
  },
  getMemory: {
    method: 'GET',
    path: p('/projects/:project_id/memories/:id'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    response: successEnvelope(memoryDetailView),
    statuses: [200],
    summary: 'Provenance, revisions and lineage of one memory.',
  },
  proposeMemory: {
    method: 'POST',
    path: p('/projects/:project_id/memories'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    body: proposeMemoryRequest,
    response: successEnvelope(memoryView),
    statuses: [201],
    summary: 'Propose a structured memory. Always a candidate, never canonical.',
  },
  previewCorrectMemory: {
    method: 'POST',
    path: p('/projects/:project_id/memories/:id:correct-preview'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    body: correctMemoryRequest.partial(),
    response: successEnvelope(previewImpact),
    statuses: [200],
    summary: 'Impact preview for a correction.',
  },
  correctMemory: {
    method: 'POST',
    path: p('/projects/:project_id/memories/:id:correct'),
    mutating: true,
    stepUp: false,
    previewToken: true,
    params: projectResourceParams,
    body: correctMemoryRequest,
    response: successEnvelope(memoryDetailView),
    statuses: [200],
    summary: 'Create a successor revision through explicit correction.',
  },
  acceptMemory: {
    method: 'POST',
    path: p('/projects/:project_id/memories/:id:accept'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    body: acceptMemoryRequest,
    response: successEnvelope(memoryDetailView),
    statuses: [200],
    summary: 'Accept a revision within the actor scope.',
  },
  markCanonical: {
    method: 'POST',
    path: p('/projects/:project_id/memories/:id:mark-canonical'),
    mutating: true,
    stepUp: true,
    previewToken: true,
    params: projectResourceParams,
    body: markCanonicalRequest,
    response: successEnvelope(memoryDetailView),
    statuses: [200],
    summary: 'Project-level canonical authority action.',
  },
  supersedeMemory: {
    method: 'POST',
    path: p('/projects/:project_id/memories/:id:supersede'),
    mutating: true,
    stepUp: false,
    previewToken: true,
    params: projectResourceParams,
    body: supersedeMemoryRequest,
    response: successEnvelope(supersedeMemoryResult),
    statuses: [200],
    summary: 'Explicit lineage mutation; history is retained.',
  },
  getCurrentDecisions: {
    method: 'GET',
    path: p('/projects/:project_id/decisions/current'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    query: pageQuery,
    response: pageEnvelope(decisionView),
    statuses: [200],
    summary: 'Current accepted decisions from the shared resolver.',
  },
  listConflicts: {
    method: 'GET',
    path: p('/projects/:project_id/conflicts'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    query: listConflictsQuery,
    response: pageEnvelope(conflictView),
    statuses: [200],
    summary: 'Active and resolved conflicts.',
  },
  resolveConflict: {
    method: 'POST',
    path: p('/projects/:project_id/conflicts/:id:resolve'),
    mutating: true,
    stepUp: false,
    previewToken: true,
    params: projectResourceParams,
    body: resolveConflictRequest,
    response: successEnvelope(resolveConflictResult),
    statuses: [200],
    summary: 'Select, merge, scope or deprecate a conflict.',
  },

  buildContextPack: {
    method: 'POST',
    path: p('/projects/:project_id/context-packs'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    body: buildContextPackRequest,
    response: successEnvelope(contextPackView),
    statuses: [200, 202],
    summary: 'Build a scoped, token-budgeted context pack.',
  },
  getContextPack: {
    method: 'GET',
    path: p('/projects/:project_id/context-packs/:id'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    response: successEnvelope(contextPackView),
    statuses: [200],
    summary: 'Retrieve an immutable context pack if still permitted.',
  },
  ask: {
    method: 'POST',
    path: p('/projects/:project_id/ask'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    body: askRequest,
    response: successEnvelope(askResult),
    statuses: [200, 202],
    summary: 'Cited project question with explicit intent and scope.',
  },
  getPulse: {
    method: 'GET',
    path: p('/projects/:project_id/pulse'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    response: successEnvelope(pulseView),
    statuses: [200],
    summary: 'Current work, recent changes, decisions and degraded status.',
  },
  listActivity: {
    method: 'GET',
    path: p('/projects/:project_id/activity'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    query: listActivityQuery,
    response: pageEnvelope(activityItem),
    statuses: [200],
    summary: 'Cursor-based normalized activity timeline.',
  },

  getSyncPolicy: {
    method: 'GET',
    path: p('/projects/:project_id/sync-policy'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    response: successEnvelope(syncPolicyView),
    statuses: [200],
    summary: 'Current effective sync policy and explanations.',
  },
  previewSyncPolicy: {
    method: 'POST',
    path: p('/projects/:project_id/sync-policy:preview'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    body: putSyncPolicyRequest.omit({ preview_token: true }),
    response: successEnvelope(syncPolicyPreviewResult),
    statuses: [200],
    summary: 'Show routing impact before a policy change.',
  },
  putSyncPolicy: {
    method: 'PUT',
    path: p('/projects/:project_id/sync-policy'),
    mutating: true,
    stepUp: true,
    previewToken: true,
    params: projectParams,
    body: putSyncPolicyRequest,
    response: successEnvelope(syncPolicyView),
    statuses: [200],
    summary: 'Create an immutable new sync-policy version.',
  },
  listDurableOperations: {
    method: 'GET',
    path: p('/projects/:project_id/durable-operations'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    query: listDurableOperationsQuery,
    response: pageEnvelope(durableOperationView),
    statuses: [200],
    summary: 'Pending, failed and persisted durable operation status.',
  },
  reconcileDurableOperation: {
    method: 'POST',
    path: p('/projects/:project_id/durable-operations/:id:reconcile'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: projectResourceParams,
    body: reconcileDurableOperationRequest,
    response: successEnvelope(durableOperationView),
    statuses: [200, 202],
    summary: 'Reconcile a MemWal/Walrus result.',
  },
  restoreNamespace: {
    method: 'POST',
    path: p('/projects/:project_id/namespaces/:id:restore'),
    mutating: true,
    stepUp: true,
    previewToken: true,
    params: projectResourceParams,
    body: restoreNamespaceRequest,
    response: acceptedEnvelope,
    statuses: [202],
    summary: 'Start a quarantined restore/reindex.',
  },

  getOperation: {
    method: 'GET',
    path: p('/operations/:id'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: z.object({ id: uuid }),
    response: successEnvelope(operationView),
    statuses: [200],
    summary: 'Poll an authorized async operation.',
  },
  cancelOperation: {
    method: 'POST',
    path: p('/operations/:id:cancel'),
    mutating: true,
    stepUp: false,
    previewToken: false,
    params: z.object({ id: uuid }),
    response: successEnvelope(operationView),
    statuses: [200],
    summary: 'Best-effort cancel before an irreversible external step.',
  },
  createExport: {
    method: 'POST',
    path: p('/projects/:project_id/exports'),
    mutating: true,
    stepUp: true,
    previewToken: true,
    params: projectParams,
    body: createExportRequest,
    response: acceptedEnvelope,
    statuses: [202],
    summary: 'Create an authorized export operation.',
  },
  deletionPreview: {
    method: 'POST',
    path: p('/projects/:project_id:deletion-preview'),
    mutating: false,
    stepUp: true,
    previewToken: false,
    params: projectParams,
    response: successEnvelope(deletionPreviewResult),
    statuses: [200],
    summary: 'Layer-by-layer deletion impact and unsupported durable guarantees.',
  },
  deleteProject: {
    method: 'DELETE',
    path: p('/projects/:project_id'),
    mutating: true,
    stepUp: true,
    previewToken: true,
    params: projectParams,
    body: deleteProjectRequest,
    response: acceptedEnvelope,
    statuses: [202],
    summary: 'Start the project deletion workflow.',
  },
  getDeletionStatus: {
    method: 'GET',
    path: p('/projects/:project_id/deletion-status'),
    mutating: false,
    stepUp: false,
    previewToken: false,
    params: projectParams,
    response: successEnvelope(deletionStatusView),
    statuses: [200],
    summary: 'Local, operational, index, backup and durable-expiry deletion states.',
  },
} as const satisfies Record<string, RouteDefinition>;

export type RouteName = keyof typeof HTTP_ROUTES;

/** Stable, sorted route signatures used by the contract snapshot fitness test (FIT-002). */
export function routeSignatures(): readonly string[] {
  return Object.values(HTTP_ROUTES)
    .map((route) => `${route.method} ${route.path}`)
    .sort();
}
